export const blogPosts = [
    {
        id: 1,
        slug: 'best-chocolate-chip-cookie-recipe',
        title: 'The Ultimate Chocolate Chip Cookie Recipe',
        excerpt: 'Learn to bake the perfect chewy chocolate chip cookie at home with our professional secret recipe.',
        category: 'Cookie Recipes',
        author: 'Priya Sharma',
        date: '2026-06-15',
        readTime: '5 min',
        emoji: '🍫',
        tags: ['Chocolate', 'Recipe', 'Baking'],
    },
    {
        id: 2,
        slug: 'healthy-oat-cookies-guide',
        title: '5 Healthy Oat Cookie Variations You Must Try',
        excerpt: 'Guilt-free cookies that are packed with nutrition and taste absolutely delicious.',
        category: 'Healthy Cookies',
        author: 'Ravi Kumar',
        date: '2026-06-10',
        readTime: '4 min',
        emoji: '🌾',
        tags: ['Healthy', 'Oatmeal', 'Sugar-Free'],
    },
    {
        id: 3,
        slug: 'cookie-gift-box-ideas',
        title: 'Best Cookie Gift Box Ideas for Every Occasion',
        excerpt: 'From birthdays to corporate gifting – find the perfect cookie hamper for everyone.',
        category: 'Gift Ideas',
        author: 'Meena Patel',
        date: '2026-06-05',
        readTime: '3 min',
        emoji: '🎁',
        tags: ['Gifts', 'Occasions', 'Corporate'],
    },
    {
        id: 4,
        slug: 'cookie-storage-tips',
        title: 'How to Keep Cookies Fresh for Longer',
        excerpt: 'Expert storage tips so your cookies stay crunchy or chewy exactly the way you love.',
        category: 'Cookie Storage Tips',
        author: 'Priya Sharma',
        date: '2026-05-28',
        readTime: '4 min',
        emoji: '📦',
        tags: ['Storage', 'Freshness', 'Tips'],
    },
    {
        id: 5,
        slug: 'vegan-cookie-baking-tips',
        title: 'Vegan Cookie Baking – Everything You Need to Know',
        excerpt: 'Butter and egg substitutes that make your vegan cookies as delicious as the real deal.',
        category: 'Baking Tips',
        author: 'Ravi Kumar',
        date: '2026-05-20',
        readTime: '6 min',
        emoji: '🌱',
        tags: ['Vegan', 'Plant-Based', 'Tips'],
    },
    {
        id: 6,
        slug: 'dessert-trends-2026',
        title: 'Top Cookie & Dessert Trends in 2026',
        excerpt: 'What are bakers and cookie lovers going crazy about this year? We break it all down.',
        category: 'Dessert Trends',
        author: 'Meena Patel',
        date: '2026-05-10',
        readTime: '5 min',
        emoji: '🍰',
        tags: ['Trends', 'Dessert', 'Baking'],
    },
];

export const blogCategories = [
    'Cookie Recipes', 'Baking Tips', 'Healthy Cookies',
    'Chocolate Lovers', 'Gift Ideas', 'Cookie Storage Tips', 'Dessert Trends',
];
